import { Dish, Restaurant } from '@/types'

export const demoRestaurant: Restaurant = {
  id: 'demo-001',
  slug: 'demo-restaurant',
  name: "Abubakar's Kitchen",
  subscription_status: 'active',
}

export const demoDishes: Dish[] = [
  {
    id: '1',
    restaurant_id: 'demo-001',
    name: 'Classic Burger',
    description: 'Juicy beef patty with lettuce, tomato, and special sauce',
    price: 850,
    category: 'Burgers',
    sort_order: 1,
    status: 'complete',
    glb_url: '/models/Burger.glb',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    restaurant_id: 'demo-001',
    name: 'Cheeseburger',
    description: 'Classic burger topped with melted cheddar cheese',
    price: 950,
    category: 'Burgers',
    sort_order: 2,
    status: 'complete',
    glb_url: '/models/Cheeseburger.glb',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    restaurant_id: 'demo-001',
    name: 'Margherita Pizza',
    description: 'Stone-baked pizza with tomato sauce and fresh mozzarella',
    price: 1200,
    category: 'Pizza',
    sort_order: 3,
    status: 'complete',
    glb_url: '/models/Pizza.glb',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    restaurant_id: 'demo-001',
    name: 'Crispy Fries',
    description: 'Golden crispy fries seasoned with sea salt',
    price: 350,
    category: 'Sides',
    sort_order: 4,
    status: 'complete',
    glb_url: '/models/Fries.glb',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    restaurant_id: 'demo-001',
    name: 'Grilled Steak',
    description: 'Premium cut grilled to perfection',
    price: 2500,
    category: 'Mains',
    sort_order: 5,
    status: 'complete',
    glb_url: '/models/Steak.glb',
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    restaurant_id: 'demo-001',
    name: 'Chicken Leg',
    description: 'Tender roasted chicken leg with herbs',
    price: 700,
    category: 'Mains',
    sort_order: 6,
    status: 'complete',
    glb_url: '/models/Chicken Leg.glb',
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    restaurant_id: 'demo-001',
    name: 'Hotdog',
    description: 'Classic hotdog in a soft bun with mustard and ketchup',
    price: 450,
    category: 'Snacks',
    sort_order: 7,
    status: 'complete',
    glb_url: '/models/Hotdog.glb',
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    restaurant_id: 'demo-001',
    name: 'Sushi',
    description: 'Fresh sushi with premium ingredients',
    price: 1500,
    category: 'Japanese',
    sort_order: 8,
    status: 'complete',
    glb_url: '/models/Sushi.glb',
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    restaurant_id: 'demo-001',
    name: 'Pancakes Stack',
    description: 'Fluffy pancakes stacked high with maple syrup',
    price: 600,
    category: 'Breakfast',
    sort_order: 9,
    status: 'complete',
    glb_url: '/models/Pancakes Stack.glb',
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    restaurant_id: 'demo-001',
    name: 'Ice Cream',
    description: 'Creamy vanilla ice cream with chocolate drizzle',
    price: 400,
    category: 'Desserts',
    sort_order: 10,
    status: 'complete',
    glb_url: '/models/Ice Cream.glb',
    created_at: new Date().toISOString(),
  },
  {
    id: '11',
    restaurant_id: 'demo-001',
    name: 'Donut',
    description: 'Glazed donut with rainbow sprinkles',
    price: 250,
    category: 'Desserts',
    sort_order: 11,
    status: 'complete',
    glb_url: '/models/Donut.glb',
    created_at: new Date().toISOString(),
  },
]
